-- SemiProject DB 파일 생성

-- 회원 정보 테이블 추가 --

CREATE TABLE "USER_INFORMATION" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"USER_GENDER"	VARCHAR2(20)		NULL,
	"AGE"	NUMBER		NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"NICK_NAME"	VARCHAR2(20)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"PHONE"	NUMBER		NOT NULL,
	"MEMBERSHIP_RATING"	VARCHAR2(20)		NOT NULL,
	"F_FOOD"	VARCHAR2(30)		NULL,
	"SORTATION"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "USER_INFORMATION"."ID" IS '아이디'; commit;

COMMENT ON COLUMN "USER_INFORMATION"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "USER_INFORMATION"."USER_GENDER" IS '성별';

COMMENT ON COLUMN "USER_INFORMATION"."AGE" IS '나이';

COMMENT ON COLUMN "USER_INFORMATION"."NAME" IS '이름';

COMMENT ON COLUMN "USER_INFORMATION"."NICK_NAME" IS '닉네임';

COMMENT ON COLUMN "USER_INFORMATION"."ADDRESS" IS '주소';

COMMENT ON COLUMN "USER_INFORMATION"."EMAIL" IS '이메일';

COMMENT ON COLUMN "USER_INFORMATION"."PHONE" IS '전화번호';

COMMENT ON COLUMN "USER_INFORMATION"."MEMBERSHIP_RATING" IS '회원별 등급';

COMMENT ON COLUMN "USER_INFORMATION"."F_FOOD" IS '선호음식선택';

COMMENT ON COLUMN "USER_INFORMATION"."SORTATION" IS '구분';

CREATE TABLE "DIET" (
	"D_CODE"	NUMBER		NOT NULL,
	"D_DATE"	DATE		NOT NULL,
	"TIME"	VARCHAR2(20)		NOT NULL,
	"FOOD_LIST"	VARCHAR2(50)		NULL,
	"MEMO"	VARCHAR2(100)		NULL,
	"F_FOOD"	VARCHAR2(50)		NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "DIET"."D_CODE" IS '식단날짜별코드';

COMMENT ON COLUMN "DIET"."D_DATE" IS '날짜선택';

COMMENT ON COLUMN "DIET"."TIME" IS '아침/점심/저녁선택';

COMMENT ON COLUMN "DIET"."FOOD_LIST" IS '식단 등록';

COMMENT ON COLUMN "DIET"."MEMO" IS '메모 기록';

COMMENT ON COLUMN "DIET"."F_FOOD" IS '선호식단등록';

COMMENT ON COLUMN "DIET"."ID" IS '아이디';

CREATE TABLE "COMMENT" (
	"COMMENT_NM"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(20)		NOT NULL,
	"WRITE_DATE"	DATE		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"B_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NM" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."WRITE_DATE" IS '작성 날짜';

COMMENT ON COLUMN "COMMENT"."ID" IS '아이디';

COMMENT ON COLUMN "COMMENT"."B_NO" IS '게시글 번호';

CREATE TABLE "PT" (
	"PT_NO"	NUMBER		NOT NULL,
	"PT_NAME"	VARCHAR2(20)		NOT NULL,
	"PT_WEIGHT"	NUMBER		NULL,
	"PT_COUNT"	NUMBER		NOT NULL,
	"PT_ID"	VARCHAR2(20)		NOT NULL,
	"LIST_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PT"."PT_NO" IS '운동의 번호';

COMMENT ON COLUMN "PT"."PT_NAME" IS '운동의 이름';

COMMENT ON COLUMN "PT"."PT_WEIGHT" IS '운동해야할 무게';

COMMENT ON COLUMN "PT"."PT_COUNT" IS '운동해야할 횟수';

COMMENT ON COLUMN "PT"."PT_ID" IS '운동아이디';

COMMENT ON COLUMN "PT"."LIST_CODE" IS '추가된 리스트의 번호';

CREATE TABLE "CHECKLIST" (
	"LIST_CODE"	NUMBER		NOT NULL,
	"LIST_CONTENTS"	VARCHAR2(100)		NULL,
	"DATE"	DATE		NOT NULL,
	"ISCHECK"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CHECKLIST"."LIST_CODE" IS '추가된 리스트의 번호';

COMMENT ON COLUMN "CHECKLIST"."LIST_CONTENTS" IS '리스트의 내용';

COMMENT ON COLUMN "CHECKLIST"."DATE" IS '날짜';

COMMENT ON COLUMN "CHECKLIST"."ISCHECK" IS '리스트 체크여부';

COMMENT ON COLUMN "CHECKLIST"."ID" IS '아이디';

CREATE TABLE "BOARD_CATEGORY" (
	"BOARD_TYPE"	VARCHAR2(200)		NOT NULL,
	"FREE_BOARD"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_CATEGORY"."BOARD_TYPE" IS '게시판 유형 선택';

COMMENT ON COLUMN "BOARD_CATEGORY"."FREE_BOARD" IS '자유/운동/상품/후기';

CREATE TABLE "REVIEW" (
	"B_NO"	NUMBER		NOT NULL,
	"STAR_RATING_WRITE"	NUMBER		NOT NULL,
	"ORDER_NUMBER"	NUMBER		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."B_NO" IS '게시글 번호';

COMMENT ON COLUMN "REVIEW"."STAR_RATING_WRITE" IS '별점 작성';

COMMENT ON COLUMN "REVIEW"."ORDER_NUMBER" IS '주문 번호';

COMMENT ON COLUMN "REVIEW"."ITEM_CODE" IS '상품 코드';

CREATE TABLE "ORDER" (
	"ORDER_NUMBER"	NUMBER		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL,
	"BUYER_NAME"	VARCHAR2(20)		NOT NULL,
	"BUYER_PHONE"	NUMBER		NOT NULL,
	"BUYER_ADDRESS"	VARCHAR2(30)		NOT NULL,
	"BUYER_REQUEST"	VARCHAR2(100)		NULL,
	"BUYER_EMAIL"	VARCHAR2(30)		NULL,
	"BUY_TOTAL"	NUMBER		NOT NULL,
	"BUY_DATE"	DATE		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_NUMBER" IS '주문 번호';

COMMENT ON COLUMN "ORDER"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "ORDER"."BUYER_NAME" IS '수령자 이름';

COMMENT ON COLUMN "ORDER"."BUYER_PHONE" IS '수령 번호';

COMMENT ON COLUMN "ORDER"."BUYER_ADDRESS" IS '수령 주소';

COMMENT ON COLUMN "ORDER"."BUYER_REQUEST" IS '수령 요청사항';

COMMENT ON COLUMN "ORDER"."BUYER_EMAIL" IS '수령자 이메일';

COMMENT ON COLUMN "ORDER"."BUY_TOTAL" IS '구매 가격';

COMMENT ON COLUMN "ORDER"."BUY_DATE" IS '구매한 날짜';

COMMENT ON COLUMN "ORDER"."ID" IS '아이디';

CREATE TABLE "CART" (
	"CART_NUMBER"	NUMBER		NOT NULL,
	"BUY_AMOUNT"	NUMBER		NULL,
	"ITEM_CODE"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CART"."CART_NUMBER" IS '장바구니 번호';

COMMENT ON COLUMN "CART"."BUY_AMOUNT" IS '구매 수량';

COMMENT ON COLUMN "CART"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "CART"."ID" IS '아이디';

CREATE TABLE "BOARD2" (
	"B_NO"	NUMBER		NOT NULL,
	"LOCAL"	VARCHAR2(20)		NOT NULL,
	"PT_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD2"."B_NO" IS '게시글번호';

COMMENT ON COLUMN "BOARD2"."LOCAL" IS '지역별  모집';

COMMENT ON COLUMN "BOARD2"."PT_ID" IS '운동 아이디';

CREATE TABLE "PRODUCT_IO" (
	"IO_NUMBER"	NUMBER		NOT NULL,
	"IO_AMOUNT"	NUMBER		NULL,
	"IO_DATE"	DATE		NOT NULL,
	"IO_STATUS"	VARCHAR2(10)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "PRODUCT_IO"."IO_NUMBER" IS '입출고 번호';

COMMENT ON COLUMN "PRODUCT_IO"."IO_AMOUNT" IS '입출고 갯수';

COMMENT ON COLUMN "PRODUCT_IO"."IO_DATE" IS '입출고 날짜';

COMMENT ON COLUMN "PRODUCT_IO"."IO_STATUS" IS '배송 상태';

COMMENT ON COLUMN "PRODUCT_IO"."ID" IS '아이디';

COMMENT ON COLUMN "PRODUCT_IO"."ITEM_CODE" IS '상품 코드';

CREATE TABLE "BOARD1" (
	"B_NO"	NUMBER		NOT NULL,
	"POST_TITLE"	VARCHAR2(200)		NOT NULL,
	"POST_CONTENT"	VARCHAR2(200)		NOT NULL,
	"POST_UPLOAD"	VARCHAR2(200)		NOT NULL,
	"NUMER_OF_VIEWS"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_TYPE"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "BOARD1"."B_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD1"."POST_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD1"."POST_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD1"."POST_UPLOAD" IS '작성일';

COMMENT ON COLUMN "BOARD1"."NUMER_OF_VIEWS" IS '조회 수';

COMMENT ON COLUMN "BOARD1"."ID" IS '아이디';

COMMENT ON COLUMN "BOARD1"."BOARD_TYPE" IS '게시판 유형 선택';

CREATE TABLE "EXERCISE" (
	"PT_ID"	VARCHAR2(20)		NOT NULL,
	"EXERCISE_TYPE"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "EXERCISE"."PT_ID" IS '운동 아이디';

COMMENT ON COLUMN "EXERCISE"."EXERCISE_TYPE" IS '가슴/어깨/등/하체/코어 등등등';

CREATE TABLE "REC" (
	"B_NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REC"."B_NO" IS '게시글번호';

COMMENT ON COLUMN "REC"."ID" IS '아이디';

CREATE TABLE "ITEM" (
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(20)		NOT NULL,
	"ITEM_PRICE"	NUMBER		NOT NULL,
	"ITEM_DETAIL"	VARCHAR2(100)		NULL,
	"ITEM_STOCK"	NUMBER		NULL,
	"ITEM_CATEGORY"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "ITEM"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "ITEM"."ITEM_NAME" IS '상품 이름';

COMMENT ON COLUMN "ITEM"."ITEM_PRICE" IS '상품 가격';

COMMENT ON COLUMN "ITEM"."ITEM_DETAIL" IS '설명/사이즈/컬러';

COMMENT ON COLUMN "ITEM"."ITEM_STOCK" IS '구매가능 재고';

COMMENT ON COLUMN "ITEM"."ITEM_CATEGORY" IS '분류';

CREATE TABLE "IMAGE" (
	"KEY"	NUMBER		NOT NULL,
	"IMAGE_LEVEL"	VARCHAR2(10)		NOT NULL,
	"IMAGE_SRC"	VARCHAR2(30)		NOT NULL,
	"IMAGE_NAME"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL,
	"D_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "IMAGE"."KEY" IS '이미지파일 번호';

COMMENT ON COLUMN "IMAGE"."IMAGE_LEVEL" IS '이미지 레벨';

COMMENT ON COLUMN "IMAGE"."IMAGE_SRC" IS '이미지파일 경로';

COMMENT ON COLUMN "IMAGE"."IMAGE_NAME" IS '이미지파일 이름';

COMMENT ON COLUMN "IMAGE"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "IMAGE"."D_CODE" IS '식단날짜별코드';

CREATE TABLE "EDIT_LIST" (
	"IMAGE_EDIT"	VARCHAR(255)		NOT NULL
);

COMMENT ON COLUMN "EDIT_LIST"."IMAGE_EDIT" IS '이미지 관리';


-- USER_INFORMATION status 탈퇴여부 컬럼 추가
ALTER TABLE USER_INFORMATION ADD(STATUS VARCHAR2(10) DEFAULT 'N');

ALTER TABLE USER_INFORMATION MODIFY STATUS NOT NULL;

COMMENT ON COLUMN USER_INFORMATION.STATUS IS '회원탈퇴여부';

ALTER TABLE USER_INFORMATION MODIFY PHONE VARCHAR2(20);

ALTER TABLE USER_INFORMATION RENAME COLUMN MEMBERSHIP_RATING TO M_RATING;
ALTER TABLE USER_INFORMATION RENAME COLUMN USER_GENDER TO GENDER;




