-- SemiProject DB 파일 생성

-- 회원 정보 테이블 추가 --

CREATE TABLE "USER_INFORMATION" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"USER_GENDER"	VARCHAR2(20)		NULL,
	"AGE"	NUMBER		NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"NICK_NAME"	VARCHAR2(20)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"PHONE"	NUMBER		NOT NULL,
	"MEMBERSHIP_RATING"	VARCHAR2(20)		NOT NULL,
	"F_FOOD"	VARCHAR2(30)		NULL,
	"SORTATION"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "USER_INFORMATION"."ID" IS '아이디'; commit;

COMMENT ON COLUMN "USER_INFORMATION"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "USER_INFORMATION"."USER_GENDER" IS '성별';

COMMENT ON COLUMN "USER_INFORMATION"."AGE" IS '나이';

COMMENT ON COLUMN "USER_INFORMATION"."NAME" IS '이름';

COMMENT ON COLUMN "USER_INFORMATION"."NICK_NAME" IS '닉네임';

COMMENT ON COLUMN "USER_INFORMATION"."ADDRESS" IS '주소';

COMMENT ON COLUMN "USER_INFORMATION"."EMAIL" IS '이메일';

COMMENT ON COLUMN "USER_INFORMATION"."PHONE" IS '전화번호';

COMMENT ON COLUMN "USER_INFORMATION"."MEMBERSHIP_RATING" IS '회원별 등급';

COMMENT ON COLUMN "USER_INFORMATION"."F_FOOD" IS '선호음식선택';

COMMENT ON COLUMN "USER_INFORMATION"."SORTATION" IS '구분';

CREATE TABLE "DIET" (
	"D_CODE"	NUMBER		NOT NULL,
	"D_DATE"	DATE		NOT NULL,
	"TIME"	VARCHAR2(20)		NOT NULL,
	"FOOD_LIST"	VARCHAR2(50)		NULL,
	"MEMO"	VARCHAR2(100)		NULL,
	"F_FOOD"	VARCHAR2(50)		NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "DIET"."D_CODE" IS '식단날짜별코드';

COMMENT ON COLUMN "DIET"."D_DATE" IS '날짜선택';

COMMENT ON COLUMN "DIET"."TIME" IS '아침/점심/저녁선택';

COMMENT ON COLUMN "DIET"."FOOD_LIST" IS '식단 등록';

COMMENT ON COLUMN "DIET"."MEMO" IS '메모 기록';

COMMENT ON COLUMN "DIET"."F_FOOD" IS '선호식단등록';

COMMENT ON COLUMN "DIET"."ID" IS '아이디';

CREATE TABLE "COMMENT" (
	"COMMENT_NM"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(20)		NOT NULL,
	"WRITE_DATE"	DATE		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"B_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NM" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."WRITE_DATE" IS '작성 날짜';

COMMENT ON COLUMN "COMMENT"."ID" IS '아이디';

COMMENT ON COLUMN "COMMENT"."B_NO" IS '게시글 번호';

CREATE TABLE "PT" (
	"PT_NO"	NUMBER		NOT NULL,
	"PT_NAME"	VARCHAR2(20)		NOT NULL,
	"PT_WEIGHT"	NUMBER		NULL,
	"PT_COUNT"	NUMBER		NOT NULL,
	"PT_ID"	VARCHAR2(20)		NOT NULL,
	"LIST_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PT"."PT_NO" IS '운동의 번호';

COMMENT ON COLUMN "PT"."PT_NAME" IS '운동의 이름';

COMMENT ON COLUMN "PT"."PT_WEIGHT" IS '운동해야할 무게';

COMMENT ON COLUMN "PT"."PT_COUNT" IS '운동해야할 횟수';

COMMENT ON COLUMN "PT"."PT_ID" IS '운동아이디';

COMMENT ON COLUMN "PT"."LIST_CODE" IS '추가된 리스트의 번호';

CREATE TABLE "CHECKLIST" (
	"LIST_CODE"	NUMBER		NOT NULL,
	"LIST_CONTENTS"	VARCHAR2(100)		NULL,
	"DATE"	DATE		NOT NULL,
	"ISCHECK"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CHECKLIST"."LIST_CODE" IS '추가된 리스트의 번호';

COMMENT ON COLUMN "CHECKLIST"."LIST_CONTENTS" IS '리스트의 내용';

COMMENT ON COLUMN "CHECKLIST"."DATE" IS '날짜';

COMMENT ON COLUMN "CHECKLIST"."ISCHECK" IS '리스트 체크여부';

COMMENT ON COLUMN "CHECKLIST"."ID" IS '아이디';

CREATE TABLE "BOARD_CATEGORY" (
	"BOARD_TYPE"	VARCHAR2(200)		NOT NULL,
	"FREE_BOARD"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_CATEGORY"."BOARD_TYPE" IS '게시판 유형 선택';

COMMENT ON COLUMN "BOARD_CATEGORY"."FREE_BOARD" IS '자유/운동/상품/후기';

CREATE TABLE "REVIEW" (
	"B_NO"	NUMBER		NOT NULL,
	"STAR_RATING_WRITE"	NUMBER		NOT NULL,
	"ORDER_NUMBER"	NUMBER		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."B_NO" IS '게시글 번호';

COMMENT ON COLUMN "REVIEW"."STAR_RATING_WRITE" IS '별점 작성';

COMMENT ON COLUMN "REVIEW"."ORDER_NUMBER" IS '주문 번호';

COMMENT ON COLUMN "REVIEW"."ITEM_CODE" IS '상품 코드';

CREATE TABLE "ORDER" (
	"ORDER_NUMBER"	NUMBER		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL,
	"BUYER_NAME"	VARCHAR2(20)		NOT NULL,
	"BUYER_PHONE"	NUMBER		NOT NULL,
	"BUYER_ADDRESS"	VARCHAR2(30)		NOT NULL,
	"BUYER_REQUEST"	VARCHAR2(100)		NULL,
	"BUYER_EMAIL"	VARCHAR2(30)		NULL,
	"BUY_TOTAL"	NUMBER		NOT NULL,
	"BUY_DATE"	DATE		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_NUMBER" IS '주문 번호';

COMMENT ON COLUMN "ORDER"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "ORDER"."BUYER_NAME" IS '수령자 이름';

COMMENT ON COLUMN "ORDER"."BUYER_PHONE" IS '수령 번호';

COMMENT ON COLUMN "ORDER"."BUYER_ADDRESS" IS '수령 주소';

COMMENT ON COLUMN "ORDER"."BUYER_REQUEST" IS '수령 요청사항';

COMMENT ON COLUMN "ORDER"."BUYER_EMAIL" IS '수령자 이메일';

COMMENT ON COLUMN "ORDER"."BUY_TOTAL" IS '구매 가격';

COMMENT ON COLUMN "ORDER"."BUY_DATE" IS '구매한 날짜';

COMMENT ON COLUMN "ORDER"."ID" IS '아이디';

CREATE TABLE "CART" (
	"CART_NUMBER"	NUMBER		NOT NULL,
	"BUY_AMOUNT"	NUMBER		NULL,
	"ITEM_CODE"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CART"."CART_NUMBER" IS '장바구니 번호';

COMMENT ON COLUMN "CART"."BUY_AMOUNT" IS '구매 수량';

COMMENT ON COLUMN "CART"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "CART"."ID" IS '아이디';

CREATE TABLE "BOARD2" (
	"B_NO"	NUMBER		NOT NULL,
	"LOCAL"	VARCHAR2(20)		NOT NULL,
	"PT_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD2"."B_NO" IS '게시글번호';

COMMENT ON COLUMN "BOARD2"."LOCAL" IS '지역별  모집';

COMMENT ON COLUMN "BOARD2"."PT_ID" IS '운동 아이디';

CREATE TABLE "PRODUCT_IO" (
	"IO_NUMBER"	NUMBER		NOT NULL,
	"IO_AMOUNT"	NUMBER		NULL,
	"IO_DATE"	DATE		NOT NULL,
	"IO_STATUS"	VARCHAR2(10)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "PRODUCT_IO"."IO_NUMBER" IS '입출고 번호';

COMMENT ON COLUMN "PRODUCT_IO"."IO_AMOUNT" IS '입출고 갯수';

COMMENT ON COLUMN "PRODUCT_IO"."IO_DATE" IS '입출고 날짜';

COMMENT ON COLUMN "PRODUCT_IO"."IO_STATUS" IS '배송 상태';

COMMENT ON COLUMN "PRODUCT_IO"."ID" IS '아이디';

COMMENT ON COLUMN "PRODUCT_IO"."ITEM_CODE" IS '상품 코드';

CREATE TABLE "BOARD1" (
	"B_NO"	NUMBER		NOT NULL,
	"POST_TITLE"	VARCHAR2(200)		NOT NULL,
	"POST_CONTENT"	VARCHAR2(200)		NOT NULL,
	"POST_UPLOAD"	VARCHAR2(200)		NOT NULL,
	"NUMER_OF_VIEWS"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_TYPE"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "BOARD1"."B_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD1"."POST_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD1"."POST_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD1"."POST_UPLOAD" IS '작성일';

COMMENT ON COLUMN "BOARD1"."NUMER_OF_VIEWS" IS '조회 수';

COMMENT ON COLUMN "BOARD1"."ID" IS '아이디';

COMMENT ON COLUMN "BOARD1"."BOARD_TYPE" IS '게시판 유형 선택';

CREATE TABLE "EXERCISE" (
	"PT_ID"	VARCHAR2(20)		NOT NULL,
	"EXERCISE_TYPE"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "EXERCISE"."PT_ID" IS '운동 아이디';

COMMENT ON COLUMN "EXERCISE"."EXERCISE_TYPE" IS '가슴/어깨/등/하체/코어 등등등';

CREATE TABLE "REC" (
	"B_NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REC"."B_NO" IS '게시글번호';

COMMENT ON COLUMN "REC"."ID" IS '아이디';

CREATE TABLE "ITEM" (
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(20)		NOT NULL,
	"ITEM_PRICE"	NUMBER		NOT NULL,
	"ITEM_DETAIL"	VARCHAR2(100)		NULL,
	"ITEM_STOCK"	NUMBER		NULL,
	"ITEM_CATEGORY"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "ITEM"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "ITEM"."ITEM_NAME" IS '상품 이름';

COMMENT ON COLUMN "ITEM"."ITEM_PRICE" IS '상품 가격';

COMMENT ON COLUMN "ITEM"."ITEM_DETAIL" IS '설명/사이즈/컬러';

COMMENT ON COLUMN "ITEM"."ITEM_STOCK" IS '구매가능 재고';

COMMENT ON COLUMN "ITEM"."ITEM_CATEGORY" IS '분류';

CREATE TABLE "IMAGE" (
	"KEY"	NUMBER		NOT NULL,
	"IMAGE_LEVEL"	VARCHAR2(10)		NOT NULL,
	"IMAGE_SRC"	VARCHAR2(30)		NOT NULL,
	"IMAGE_NAME"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE"	VARCHAR2(10)		NOT NULL,
	"D_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "IMAGE"."KEY" IS '이미지파일 번호';

COMMENT ON COLUMN "IMAGE"."IMAGE_LEVEL" IS '이미지 레벨';

COMMENT ON COLUMN "IMAGE"."IMAGE_SRC" IS '이미지파일 경로';

COMMENT ON COLUMN "IMAGE"."IMAGE_NAME" IS '이미지파일 이름';

COMMENT ON COLUMN "IMAGE"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "IMAGE"."D_CODE" IS '식단날짜별코드';

CREATE TABLE "EDIT_LIST" (
	"IMAGE_EDIT"	VARCHAR(255)		NOT NULL
);

COMMENT ON COLUMN "EDIT_LIST"."IMAGE_EDIT" IS '이미지 관리';


-- USER_INFORMATION status 탈퇴여부 컬럼 추가
ALTER TABLE USER_INFORMATION ADD(STATUS VARCHAR2(10) DEFAULT 'N');

ALTER TABLE USER_INFORMATION MODIFY STATUS NOT NULL;

COMMENT ON COLUMN USER_INFORMATION.STATUS IS '회원탈퇴여부';

ALTER TABLE USER_INFORMATION MODIFY PHONE VARCHAR2(20);
ALTER TABLE USER_INFORMATION RENAME COLUMN MEMBERSHIP_RATING TO M_RATING;
ALTER TABLE USER_INFORMATION RENAME COLUMN USER_GENDER TO GENDER;

ALTER TABLE USER_INFORMATION MODIFY M_RATING NULL;
ALTER TABLE USER_INFORMATION MODIFY SORTATION NULL;
ALTER TABLE USER_INFORMATION MODIFY STATUS NULL;

DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE BOARD1 CASCADE CONSTRAINTS;
DROP TABLE BOARD2 CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IO CASCADE CONSTRAINTS;
DROP TABLE BOARD1 CASCADE CONSTRAINTS;
DROP TABLE EXERCISE CASCADE CONSTRAINTS;
DROP TABLE REC CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE IMAGE CASCADE CONSTRAINTS;
DROP TABLE EDIT_LIST CASCADE CONSTRAINTS;
DROP TABLE USER_INFORMATION CASCADE CONSTRAINTS;
DROP TABLE DIET CASCADE CONSTRAINTS;
DROP TABLE PT CASCADE CONSTRAINTS;
DROP TABLE CHECKLIST CASCADE CONSTRAINTS;
DROP TABLE BOARD_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;


CREATE TABLE "DIET" (
	"D_CODE"	NUMBER		NOT NULL,
	"D_DATE"	DATE		NOT NULL,
	"MEMO"	VARCHAR2(3000)		NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "DIET"."D_CODE" IS '식단날짜별코드';

COMMENT ON COLUMN "DIET"."D_DATE" IS '날짜선택';

COMMENT ON COLUMN "DIET"."MEMO" IS '메모 기록';

COMMENT ON COLUMN "DIET"."ID" IS '아이디';

CREATE TABLE "COMMENT" (
	"COMMENT_NM"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"WRITE_DATE"	DATE		NOT NULL,
	"ID"	VARCHAR2(1000)		NOT NULL,
	"B_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NM" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."WRITE_DATE" IS '작성 날짜';

COMMENT ON COLUMN "COMMENT"."ID" IS '아이디';

COMMENT ON COLUMN "COMMENT"."B_NO" IS '게시글 번호';

CREATE TABLE "CHECKLIST" (
	"LIST_CODE"	NUMBER		NOT NULL,
	"ISCHECK"	NUMBER		NULL,
	"LIST_CONTENTS"	VARCHAR2(100)		NULL,
	"LIST_COUNT"	NUMBER		NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CHECKLIST"."LIST_CODE" IS '추가된 리스트의 번호';

COMMENT ON COLUMN "CHECKLIST"."ISCHECK" IS '리스트 체크여부';

COMMENT ON COLUMN "CHECKLIST"."LIST_CONTENTS" IS '리스트의 내용';

COMMENT ON COLUMN "CHECKLIST"."LIST_COUNT" IS '날짜';

COMMENT ON COLUMN "CHECKLIST"."ID" IS '아이디';

CREATE TABLE "REVIEW" (
	"ORDER_NUMBER"	NUMBER		NOT NULL,
	"ITEM_CODE"	VARCHAR2(1000)		NOT NULL,
	"BUYER_E"	VARCHAR2(1000)		NOT NULL,
	"BUYER_N"	VARCHAR2(1000)		NOT NULL,
	"BUYER_R"	VARCHAR2(4000)		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."ORDER_NUMBER" IS '주문 번호';

COMMENT ON COLUMN "REVIEW"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "REVIEW"."BUYER_E" IS '구매자 이메일';

COMMENT ON COLUMN "REVIEW"."BUYER_N" IS '구매자 이름';

COMMENT ON COLUMN "REVIEW"."BUYER_R" IS '구매자 리뷰';

CREATE TABLE "ORDER" (
	"ORDER_NUMBER"	NUMBER		NOT NULL,
	"ITEM_CODE"	VARCHAR2(1000)		NOT NULL,
	"BUYER_NAME"	VARCHAR2(1000)		NOT NULL,
	"BUYER_PHONE"	NUMBER		NOT NULL,
	"BUYER_ADDRESS"	VARCHAR2(3000)		NOT NULL,
	"BUYER_REQUEST"	VARCHAR2(3000)		NULL,
	"BUYER_EMAIL"	VARCHAR2(1500)		NULL,
	"BUY_TOTAL"	NUMBER		NOT NULL,
	"BUY_DATE"	DATE		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_NUMBER" IS '주문 번호';

COMMENT ON COLUMN "ORDER"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "ORDER"."BUYER_NAME" IS '수령자 이름';

COMMENT ON COLUMN "ORDER"."BUYER_PHONE" IS '수령 번호';

COMMENT ON COLUMN "ORDER"."BUYER_ADDRESS" IS '수령 주소';

COMMENT ON COLUMN "ORDER"."BUYER_REQUEST" IS '수령 요청사항';

COMMENT ON COLUMN "ORDER"."BUYER_EMAIL" IS '수령자 이메일';

COMMENT ON COLUMN "ORDER"."BUY_TOTAL" IS '구매 가격';

COMMENT ON COLUMN "ORDER"."BUY_DATE" IS '구매한 날짜';

COMMENT ON COLUMN "ORDER"."ID" IS '아이디';

CREATE TABLE "CART" (
	"CART_NUMBER"	NUMBER		NOT NULL,
	"BUY_AMOUNT"	NUMBER		NULL,
	"ITEM_CODE"	VARCHAR2(1000)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CART"."CART_NUMBER" IS '장바구니 번호';

COMMENT ON COLUMN "CART"."BUY_AMOUNT" IS '구매 수량';

COMMENT ON COLUMN "CART"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "CART"."ID" IS '아이디';

CREATE TABLE "BOARD" (
	"B_NO"	NUMBER		NOT NULL,
	"PS_TITLE"	VARCHAR2(200)		NOT NULL,
	"PS_CONTENT"	VARCHAR2(200)		NOT NULL,
	"PS_DATE"	DATE		NOT NULL,
	"NO_VIEWS"	NUMBER		NOT NULL,
	"STATUS"	VARCHAR2(200)		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"PT_NO"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD"."B_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."PS_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."PS_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."PS_DATE" IS '작성일';

COMMENT ON COLUMN "BOARD"."NO_VIEWS" IS '조회 수';

COMMENT ON COLUMN "BOARD"."STATUS" IS '상태값';

COMMENT ON COLUMN "BOARD"."COMMENT_NO" IS '댓글 수';

COMMENT ON COLUMN "BOARD"."ID" IS '아이디';

COMMENT ON COLUMN "BOARD"."PT_NO" IS '운동 번호';

CREATE TABLE "EXERCISE" (
	"PT_NO"	VARCHAR2(20)		NOT NULL,
	"EXERCISE_TYPE"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "EXERCISE"."PT_NO" IS '운동 번호';

COMMENT ON COLUMN "EXERCISE"."EXERCISE_TYPE" IS '테니스/등산/마라톤 등등';

CREATE TABLE "ITEM" (
	"ITEM_CODE"	VARCHAR2(1000)		NOT NULL,
	"ITEM_NAME"	VARCHAR2(4000)		NOT NULL,
	"ITEM_PRICE"	VARCHAR2(1000)		NOT NULL,
	"ITEM_DESC"	VARCHAR2(4000)		NOT NULL,
	"ITEM_IFM"	VARCHAR2(2000)		NOT NULL,
	"ITEM_CATEGORY"	VARCHAR2(500)		NOT NULL,
	"ITEM_DETAIL2"	VARCHAR2(500)		NOT NULL,
	"ITEM_SIZE"	VARCHAR2(2000)		NOT NULL,
	"ITEM_URL"	VARCHAR2(4000)		NOT NULL,
	"ITEM_LOGO"	VARCHAR2(4000)		NOT NULL,
	"ITEM_STOCK"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "ITEM"."ITEM_CODE" IS '상품 코드';

COMMENT ON COLUMN "ITEM"."ITEM_NAME" IS '상품 이름';

COMMENT ON COLUMN "ITEM"."ITEM_PRICE" IS '상품 가격';

COMMENT ON COLUMN "ITEM"."ITEM_DESC" IS '상품 설명';

COMMENT ON COLUMN "ITEM"."ITEM_IFM" IS '상품 정보';

COMMENT ON COLUMN "ITEM"."ITEM_CATEGORY" IS '분류';

COMMENT ON COLUMN "ITEM"."ITEM_DETAIL2" IS '컬러';

COMMENT ON COLUMN "ITEM"."ITEM_SIZE" IS '사이즈';

COMMENT ON COLUMN "ITEM"."ITEM_URL" IS '상품 이미지';

COMMENT ON COLUMN "ITEM"."ITEM_LOGO" IS '상품 로고';

COMMENT ON COLUMN "ITEM"."ITEM_STOCK" IS '상품 재고';

CREATE TABLE "IMAGE" (
	"KEY"	NUMBER		NOT NULL,
	"IMAGE_SRC"	VARCHAR2(30)		NOT NULL,
	"IMAGE_NAME"	VARCHAR2(20)		NOT NULL,
	"D_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "IMAGE"."KEY" IS '이미지파일 번호';

COMMENT ON COLUMN "IMAGE"."IMAGE_SRC" IS '이미지파일 경로';

COMMENT ON COLUMN "IMAGE"."IMAGE_NAME" IS '이미지파일 이름';

COMMENT ON COLUMN "IMAGE"."D_CODE" IS '식단날짜별코드';

CREATE TABLE "EDIT_LIST" (
	"IMAGE_EDIT"	VARCHAR(255)		NOT NULL
);

COMMENT ON COLUMN "EDIT_LIST"."IMAGE_EDIT" IS '이미지 관리';

CREATE TABLE "USER_INFORMATION" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"GENDER"	VARCHAR2(20)		NOT NULL,
	"AGE"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"NICK_NAME"	VARCHAR2(20)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"PHONE"	VARCHAR(20)		NOT NULL,
	"M_RATING"	VARCHAR2(50)		NULL,
	"F_FOOD"	VARCHAR2(100)		NULL,
	"SORTATION"	VARCHAR2(200)		NULL,
	"STATUS"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "USER_INFORMATION"."ID" IS '아이디';

COMMENT ON COLUMN "USER_INFORMATION"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "USER_INFORMATION"."GENDER" IS '성별';

COMMENT ON COLUMN "USER_INFORMATION"."AGE" IS '나이';

COMMENT ON COLUMN "USER_INFORMATION"."NAME" IS '이름';

COMMENT ON COLUMN "USER_INFORMATION"."NICK_NAME" IS '닉네임';

COMMENT ON COLUMN "USER_INFORMATION"."ADDRESS" IS '주소';

COMMENT ON COLUMN "USER_INFORMATION"."EMAIL" IS '이메일';

COMMENT ON COLUMN "USER_INFORMATION"."PHONE" IS '전화번호';

COMMENT ON COLUMN "USER_INFORMATION"."M_RATING" IS '회원별 등급';

COMMENT ON COLUMN "USER_INFORMATION"."F_FOOD" IS '선호음식선택';

COMMENT ON COLUMN "USER_INFORMATION"."SORTATION" IS '구분';

COMMENT ON COLUMN "USER_INFORMATION"."STATUS" IS '회원탈퇴여부';

CREATE TABLE "PT" (
	"PT_NO"	NUMBER		NOT NULL,
	"PT_NAME"	VARCHAR2(100)		NOT NULL,
	"PT_TYPE"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "PT"."PT_NO" IS '운동의 번호';

COMMENT ON COLUMN "PT"."PT_NAME" IS '운동의 이름';

COMMENT ON COLUMN "PT"."PT_TYPE" IS '운동의 부위';

ALTER TABLE "DIET" ADD CONSTRAINT "PK_DIET" PRIMARY KEY (
	"D_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NM"
);

ALTER TABLE "CHECKLIST" ADD CONSTRAINT "PK_CHECKLIST" PRIMARY KEY (
	"LIST_CODE"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"ORDER_NUMBER",
	"ITEM_CODE"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_NUMBER",
	"ITEM_CODE"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"CART_NUMBER"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"B_NO"
);

ALTER TABLE "EXERCISE" ADD CONSTRAINT "PK_EXERCISE" PRIMARY KEY (
	"PT_NO"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY (
	"ITEM_CODE"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "PK_IMAGE" PRIMARY KEY (
	"KEY"
);

ALTER TABLE "USER_INFORMATION" ADD CONSTRAINT "PK_USER_INFORMATION" PRIMARY KEY (
	"ID"
);

ALTER TABLE "PT" ADD CONSTRAINT "PK_PT" PRIMARY KEY (
	"PT_NO"
);

ALTER TABLE "DIET" ADD CONSTRAINT "FK_USER_INFORMATION_TO_DIET_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USER_INFORMATION" (
	"ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_USER_INFORMATION_TO_COMMENT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USER_INFORMATION" (
	"ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"B_NO"
)
REFERENCES "BOARD" (
	"B_NO"
);

ALTER TABLE "CHECKLIST" ADD CONSTRAINT "FK_USER_INFORMATION_TO_CHECKLIST_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USER_INFORMATION" (
	"ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_ORDER_TO_REVIEW_1" FOREIGN KEY (
	"ORDER_NUMBER"
)
REFERENCES "ORDER" (
	"ORDER_NUMBER"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_ORDER_TO_REVIEW_2" FOREIGN KEY (
	"ITEM_CODE"
)
REFERENCES "ORDER" (
	"ITEM_CODE"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_ITEM_TO_ORDER_1" FOREIGN KEY (
	"ITEM_CODE"
)
REFERENCES "ITEM" (
	"ITEM_CODE"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_USER_INFORMATION_TO_ORDER_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USER_INFORMATION" (
	"ID"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_ITEM_TO_CART_1" FOREIGN KEY (
	"ITEM_CODE"
)
REFERENCES "ITEM" (
	"ITEM_CODE"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_USER_INFORMATION_TO_CART_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USER_INFORMATION" (
	"ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_USER_INFORMATION_TO_BOARD_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USER_INFORMATION" (
	"ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_EXERCISE_TO_BOARD_1" FOREIGN KEY (
	"PT_NO"
)
REFERENCES "EXERCISE" (
	"PT_NO"
);

ALTER TABLE "IMAGE" ADD CONSTRAINT "FK_DIET_TO_IMAGE_1" FOREIGN KEY (
	"D_CODE"
)
REFERENCES "DIET" (
	"D_CODE"
);
